/*
 * OpenHack
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace TriviaAPI.Models
{ 
    /// <summary>
    /// Question for the Trivia API
    /// </summary>
    [DataContract]
    public partial class QuestionModel : IEquatable<QuestionModel>
    { 
        /// <summary>
        /// Question Id
        /// </summary>
        /// <value>Question Id</value>
        [DataMember(Name="id")]
        public int? Id { get; set; }

        /// <summary>
        /// Question text
        /// </summary>
        /// <value>Question text</value>
        [DataMember(Name="text")]
        public string Text { get; set; }

        /// <summary>
        /// Possible answers for the question
        /// </summary>
        /// <value>Possible answers for the question</value>
        [DataMember(Name="questionOptions")]
        public List<QuestionOptionModel> QuestionOptions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QuestionModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  QuestionOptions: ").Append(QuestionOptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((QuestionModel)obj);
        }

        /// <summary>
        /// Returns true if QuestionModel instances are equal
        /// </summary>
        /// <param name="other">Instance of QuestionModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QuestionModel other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Text == other.Text ||
                    Text != null &&
                    Text.Equals(other.Text)
                ) && 
                (
                    QuestionOptions == other.QuestionOptions ||
                    QuestionOptions != null &&
                    QuestionOptions.SequenceEqual(other.QuestionOptions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Text != null)
                    hashCode = hashCode * 59 + Text.GetHashCode();
                    if (QuestionOptions != null)
                    hashCode = hashCode * 59 + QuestionOptions.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(QuestionModel left, QuestionModel right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(QuestionModel left, QuestionModel right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
